CREATE DATABASE DSWAYDIBDIB;
GO

USE DSWAYDIBDIB;
GO

CREATE TABLE Product_Info (
    ProductID INT IDENTITY(1,1) PRIMARY KEY,
    ItemName VARCHAR(100) NOT NULL,
    Price DECIMAL(10,2) NOT NULL,
    Description VARCHAR(50) NOT NULL,
    Category VARCHAR(50) NULL
);

CREATE DATABASE SimpleUserDB;
GO

USE SimpleUserDB;
GO

CREATE TABLE Users (
    UserID INT IDENTITY(1,1) PRIMARY KEY,
    Username VARCHAR(50) UNIQUE NOT NULL,
    Password VARCHAR(100) NOT NULL
);
SELECT * FROM Users;